version: "3"
services:
  node:
    build: .
    ports:
     - 3000:3000
    container_name: nodejs_Richam
  mongodb:
    image : mongo
    container_name: mongodb_Richam
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
     - 8080:8080
