# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu1804"
  config.vm.network :private_network, ip: "192.168.57.10"
  config.vm.network :forwarded_port, guest: 3000, host: 80

  config.vm.provider "virtualbox" do |vb|
    vb.name = "nodejs"
    vb.gui = false
    vb.memory = "1024"
    vb.cpus = 1
  end
  
  config.vm.provision "shell", path: "scripts/update.sh"
  config.vm.provision "shell", path: "scripts/install_nodejs.sh"
  config.vm.provision "shell", path: "scripts/install_git.sh"
  config.vm.provision "shell", path: "scripts/install_mongodb.sh"


end
