name: run unit tests
on: [push]
jobs:
  unit-tests:
    runs-on: debian-latest
    defaults:
      run:
        working-directory: website
    services:
      mongodb:
        image: mongo
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-nodes@v2
        with: 
          node-version: '17'
      - run: npm ci
      - run: npm test
      